name: "DNS POC (Single)"
description: "Create/Update a Route 53 record (supports Alias)"
title: "[POC DNS] <create|update> <type> <name> in <zone>"
labels: ["dns", "poc"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        ## How this form works
        - **Choose an Action** below: **create** or **update**.
        - Fill the **Target** section (Zone, Name, Type).  
          - For **update**, *Type must be the **current** type* in Terraform.
        - For **create**, use the **Create fields** (`TTL`, `Values` **or** `Alias`).
        - For **update**, use the **Update-only fields** (`new_*`) to change things.  
          - Leave any **new_*** field **blank** to keep it unchanged.
        - **Do not type** “No response” — just leave fields empty. (We treat empty fields as “don’t change”.)

  - type: input
    id: snow_id
    attributes:
      label: SNOW Request/Task ID
      placeholder: RITM0123456 or TASK0123456
      description: "Your ServiceNow request/task (e.g., RITM/TASK/CHG)."
    validations:
      required: true

  - type: dropdown
    id: action
    attributes:
      label: Action
      options: ["create","update"]
      description: "Choose 'create' to add a record, 'update' to modify an existing one."
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        ---
        ## Target (existing or new)
        These identify the record:
        - **Zone** must be an FQDN with a trailing dot (e.g., `example.com.`).
        - **Record name** may be relative (`www`) or FQDN (`www.example.com.`).  
          Relative names will be resolved under the Zone.
        - **Type** is the **current** type for updates.

  - type: input
    id: zone
    attributes:
      label: Zone (must end with a dot)
      placeholder: example.com.
      description: "Hosted zone FQDN, e.g., example.com."
    validations:
      required: true

  - type: input
    id: name
    attributes:
      label: Record name (relative or FQDN)
      placeholder: www
      description: "Relative (e.g., www) or FQDN (e.g., www.example.com.)."
    validations:
      required: true

  - type: dropdown
    id: type
    attributes:
      label: Type (CURRENT type for updates)
      options: ["A","AAAA","CNAME","MX","TXT","NS"]
      description: "For update, this is the CURRENT type in TF."
    validations:
      required: true

  - type: dropdown
    id: variant
    attributes:
      label: Variant (create) / New variant (update, optional)
      options: ["standard","alias"]
      description: "Alias is valid only for A/AAAA."
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        ---
        ## Create fields (or baseline values)
        Use these when **creating** a standard record, or to provide baseline values.
        - **TTL** (seconds). Leave blank for Alias records (TTL not used with Alias).
        - **Values** (one per line).  
          - **A/AAAA:** one IP per line  
          - **CNAME:** single FQDN target (e.g., `target.example.net.`)  
          - **MX:** `priority host.` (e.g., `10 mail.example.com.`)  
          - **TXT:** one string per line  
          - **NS:** one nameserver per line, with trailing dot
        - **Alias** (A/AAAA only): provide target DNS name, target hosted zone ID, and whether to evaluate target health.

  - type: input
    id: ttl
    attributes:
      label: TTL (seconds)
      placeholder: "300"
      description: "Leave blank for alias records (TTL not used with alias)."
    validations:
      required: false

  - type: textarea
    id: values
    attributes:
      label: Values (one per line)
      description: |
        A/AAAA: one IP per line
        CNAME: single FQDN (e.g., target.example.net.)
        MX: one per line as "priority host." (e.g., 10 mail.example.com.)
        TXT: one string per line
        NS: one nameserver per line (with trailing dot)
      render: text
    validations:
      required: false

  - type: input
    id: alias_target
    attributes:
      label: Alias target DNS name
      placeholder: d123.cloudfront.net.
      description: "FQDN of the AWS target (must end with a dot). A/AAAA only."
    validations:
      required: false

  - type: input
    id: alias_zone_id
    attributes:
      label: Alias target hosted zone ID
      placeholder: Z2FDTNDATAQYW2
      description: "AWS hosted zone ID of the target (e.g., CloudFront: Z2FDTNDATAQYW2)."
    validations:
      required: false

  - type: dropdown
    id: alias_eth
    attributes:
      label: Evaluate target health
      options: ["false","true"]
    validations:
      required: false

  - type: markdown
    attributes:
      value: |
        ---
        ## Update-only fields (leave blank to keep existing)
        Use these **only when Action = update**.  
        - This is a **merge** update: fields you fill here will be changed; everything else remains as-is.
        - To change to **CNAME**, provide **New type = CNAME** and a **single** New value.
        - To switch to **Alias**, provide **New alias target** and **New alias hosted zone ID** (A/AAAA only).
        - **Do not type** “No response”. Just leave fields blank if you’re not changing them.

  - type: input
    id: new_name
    attributes:
      label: New record name (optional, update)
      placeholder: api-v2
      description: "Leave blank to keep the same name."
    validations:
      required: false

  - type: dropdown
    id: new_type
    attributes:
      label: New type (optional, update)
      options: ["", "A","AAAA","CNAME","MX","TXT","NS"]
      description: "Leave blank to keep the same type."
    validations:
      required: false

  - type: input
    id: new_ttl
    attributes:
      label: New TTL (optional, update)
      placeholder: "60"
      description: "Leave blank to keep the same TTL."
    validations:
      required: false

  - type: textarea
    id: new_values
    attributes:
      label: New values (optional, update)
      description: "Values to replace existing 'records' (one per line). Leave blank to keep current values."
      render: text
    validations:
      required: false

  - type: input
    id: new_alias_target
    attributes:
      label: New alias target (optional, update)
      placeholder: d111111abcdef8.cloudfront.net.
      description: "Supply with new alias_zone_id if switching to alias (A/AAAA only)."
    validations:
      required: false

  - type: input
    id: new_alias_zone_id
    attributes:
      label: New alias hosted zone ID (optional, update)
      placeholder: Z2FDTNDATAQYW2
      description: "Required if switching to alias (A/AAAA only)."
    validations:
      required: false

  - type: dropdown
    id: new_alias_eth
    attributes:
      label: New alias evaluate_target_health (optional, update)
      options: ["", "false","true"]
    validations:
      required: false

  - type: markdown
    attributes:
      value: |
        ---
        ### Notes & rules
        - **Alias is A/AAAA only.** If you supply an alias, `records` and `ttl` will be ignored/removed.
        - **CNAME requires exactly one value.** (e.g., `edge.example.net.`)
        - **Trailing dot**: use it for FQDNs (e.g., `example.com.`). Relative names are supported.
        - **No routing policies** (weighted, failover) in this POC.
        - We’ll open a PR with the change if validation passes.

  - type: textarea
    id: justification
    attributes:
      label: Business justification (optional)
      render: text
