name: "DNS POC"
description: "Create/Update a Route53 record (POC)"
title: "[POC DNS] <create|update> <type> <name> in <zone>"
labels: ["poc", "dns"]
body:
  - type: dropdown
    id: action
    attributes: { label: Action, options: ["create","update"] }
    validations: { required: true }
  - type: input
    id: zone
    attributes: { label: "Zone (must end with .)", placeholder: "example.com." }
    validations: { required: true }
  - type: input
    id: name
    attributes: { label: "Record name (relative or FQDN)", placeholder: "www" }
    validations: { required: true }
  - type: dropdown
    id: type
    attributes: { label: "Type", options: ["A","AAAA","CNAME","TXT","MX"] }
    validations: { required: true }
  - type: input
    id: ttl
    attributes: { label: "TTL (s)", placeholder: "300" }
    validations: { required: true }
  - type: textarea
    id: values
    attributes: { label: "Values (one per line)", render: text }
    validations: { required: true }
