name: "DNS POC (Single)"
description: "Create/Update a Route 53 record (supports Alias)"
title: "[POC DNS] <create|update> <type> <name> in <zone>"
labels: ["dns", "poc"]
assignees: []
body:
  - type: input
    id: snow_id
    attributes:
      label: SNOW Request/Task ID
      placeholder: RITM0123456 or TASK0123456
      description: "Your ServiceNow request/task (e.g., RITM/TASK/CHG)."
    validations:
      required: true

  - type: dropdown
    id: action
    attributes:
      label: Action
      options: ["create","update"]
      description: "Choose 'create' to add a record, 'update' to modify an existing one."
    validations:
      required: true

  # ---- Target (existing or new) ----
  - type: input
    id: zone
    attributes:
      label: Zone (must end with a dot)
      placeholder: example.com.
      description: "Hosted zone FQDN, e.g., example.com."
    validations:
      required: true

  - type: input
    id: name
    attributes:
      label: Record name (relative or FQDN)
      placeholder: www
      description: "Relative (e.g., www) or FQDN (e.g., www.example.com.)."
    validations:
      required: true

  - type: dropdown
    id: type
    attributes:
      label: Type (CURRENT type for updates)
      options: ["A","AAAA","CNAME","MX","TXT","NS"]
      description: "For update, this is the CURRENT type in TF."
    validations:
      required: true

  - type: dropdown
    id: variant
    attributes:
      label: Variant (create) / New variant (update, optional)
      options: ["standard","alias"]
      description: "Alias is valid only for A/AAAA."
    validations:
      required: true

  # ---- Fields for CREATE (standard) OR UPDATE (new values) ----
  - type: input
    id: ttl
    attributes:
      label: TTL (seconds)
      placeholder: "300"
      description: "Leave blank for alias records (TTL not used with alias)."
    validations:
      required: false

  - type: textarea
    id: values
    attributes:
      label: Values (one per line)
      description: |
        A/AAAA: one IP per line
        CNAME: single FQDN (e.g., target.example.net.)
        MX: one per line as "priority host." (e.g., 10 mail.example.com.)
        TXT: one string per line
        NS: one nameserver per line (with trailing dot)
      render: text
    validations:
      required: false

  # ---- ALIAS (create or update) ----
  - type: input
    id: alias_target
    attributes:
      label: Alias target DNS name
      placeholder: d123.cloudfront.net.
      description: "FQDN of the AWS target (must end with a dot). A/AAAA only."
    validations:
      required: false

  - type: input
    id: alias_zone_id
    attributes:
      label: Alias target hosted zone ID
      placeholder: Z2FDTNDATAQYW2
      description: "AWS hosted zone ID of the target (e.g., CloudFront: Z2FDTNDATAQYW2)."
    validations:
      required: false

  - type: dropdown
    id: alias_eth
    attributes:
      label: Evaluate target health
      options: ["false","true"]
      description: "Route 53 alias setting: evaluate_target_health."
    validations:
      required: false

  # ---- UPDATE-ONLY (optional change fields) ----
  - type: input
    id: new_name
    attributes:
      label: New record name (optional, update)
      placeholder: api-v2
      description: "Leave blank to keep the same name."
    validations:
      required: false

  - type: dropdown
    id: new_type
    attributes:
      label: New type (optional, update)
      options: ["", "A","AAAA","CNAME","MX","TXT","NS"]
      description: "Leave blank to keep the same type."
    validations:
      required: false

  - type: input
    id: new_ttl
    attributes:
      label: New TTL (optional, update)
      placeholder: "60"
      description: "Leave blank to keep the same TTL."
    validations:
      required: false

  - type: textarea
    id: new_values
    attributes:
      label: New values (optional, update)
      description: "Values to replace existing 'records' (one per line)."
      render: text
    validations:
      required: false

  - type: input
    id: new_alias_target
    attributes:
      label: New alias target (optional, update)
      placeholder: d111111abcdef8.cloudfront.net.
      description: "Supply with new alias_zone_id if switching to alias."
    validations:
      required: false

  - type: input
    id: new_alias_zone_id
    attributes:
      label: New alias hosted zone ID (optional, update)
      placeholder: Z2FDTNDATAQYW2
      description: "Required if switching to alias."
    validations:
      required: false

  - type: dropdown
    id: new_alias_eth
    attributes:
      label: New alias evaluate_target_health (optional, update)
      options: ["", "false","true"]
    validations:
      required: false

  - type: textarea
    id: justification
    attributes:
      label: Business justification (optional)
      render: text
